set sigs [list]
lappend sigs "tb_rv_icache.uut.clk"
lappend sigs "tb_rv_icache.uut.rst_n"
lappend sigs "tb_rv_icache.uut.cpu_addr"
lappend sigs "tb_rv_icache.uut.cpu_req"
lappend sigs "tb_rv_icache.uut.invalidate"
lappend sigs "tb_rv_icache.uut.m_arready"
lappend sigs "tb_rv_icache.uut.m_rvalid"
lappend sigs "tb_rv_icache.uut.m_rdata"
lappend sigs "tb_rv_icache.uut.m_rlast"
lappend sigs "tb_rv_icache.uut.m_rresp"
lappend sigs "tb_rv_icache.uut.cpu_rdata"
lappend sigs "tb_rv_icache.uut.cpu_valid"
lappend sigs "tb_rv_icache.uut.cpu_stall"
lappend sigs "tb_rv_icache.uut.m_arvalid"
lappend sigs "tb_rv_icache.uut.m_araddr"
lappend sigs "tb_rv_icache.uut.m_arlen"
lappend sigs "tb_rv_icache.uut.m_arsize"
lappend sigs "tb_rv_icache.uut.m_arburst"
lappend sigs "tb_rv_icache.uut.m_rready"
lappend sigs "tb_rv_icache.uut.ecc_1bit"
lappend sigs "tb_rv_icache.uut.ecc_2bit"
gtkwave::addSignalsFromList $sigs
gtkwave::/Time/Zoom/Zoom_Full
